# Generated by Django 5.0.2 on 2024-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reg_number',
            field=models.CharField(default='C025-01-0811/2022', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
