# Generated by Django 5.0.2 on 2024-02-27 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_performance_semester_remove_performance_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 11, 13, 6, 529395, tzinfo=datetime.timezone.utc)),
        ),
    ]
