# Generated by Django 5.0.2 on 2024-03-02 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='break_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_goal',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='customuser',
            name='focus_period',
            field=models.IntegerField(default=25),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration_mins', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('goal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
