# Generated by Django 5.0.2 on 2024-03-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_break_duration_customuser_daily_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_duration_sec',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
