# Generated by Django 5.0.2 on 2024-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_session_session_duration_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
