# Generated by Django 5.0.2 on 2024-03-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='outline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
