# Generated by Django 5.0.2 on 2024-03-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_unit_outline_alter_resource_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='main.unit'),
        ),
    ]
