# Generated by Django 5.0.2 on 2024-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_resource_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='grade',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
